### ISSUE TITLE
Allow an optional string to precede dates in the date list

### ISSUE THREAD

**Issue by ghost** [FilipOsowski/howmuchtime#1]
It would be nice if we could attach a name to each date. Could this feature be added? I'm happy to provide a PR for this. @FilipOsowski

**Comment by FilipOsowski** [comment]
Sure, I'd appreciate the PR!

**Comment by ghost** [comment]
Okay, I'll fork the repo and get to work.

**Comment by ghost** [comment]
I think that this feature would be a great improvement to the program but I've decided not to continue working on it at this time. If no one else provides a pull request I may provide one in the future.

**Comment by FilipOsowski** [comment]
No problem. I don't have much time at the moment but I'll probably work on the feature myself sometime later.

**Comment by FilipOsowski** [comment]
This feature has been added. Use `hmt -a <date> <optional name>` to add a name to your date. You can also remove a date using its name: `hmt-r <name>`. Sorry for the long wait!
